services:

  nginx:
    build: ./mern/nginx  # Build from the Dockerfile in ./nginx directory
    ports:
      - "80:80"  # Expose port 80 for Nginx reverse proxy
    networks:
      - mern_network
    depends_on:
      - frontend
      - backend

  backend:
    build: ./mern/backend
    ports:
      - "5050:5050" 
    networks:
      - mern_network
    environment:
      MONGO_URI: mongodb://mongo:27018/mydatabase  
    depends_on:
      - mongodb

  frontend:
    build: ./mern/frontend
    ports:
      - "5173:5173" 
    networks:
      - mern_network
    environment:
      REACT_APP_API_URL: http://backend:5050 
  
  
  mongodb:
    image: mongo:latest  
    ports:
      - "27018:27018"  
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db  



networks:
  mern_network:
    driver: bridge 

volumes:
  mongo-data:
    driver: local  # Persist MongoDB data locally

